/*
 * @(#)DomconOzOutputCodec.java created 03.02.2006
 * 
 * Copyright (c) 2006 Alexander Koller
 *  
 */

package de.saar.chorus.domgraph.codec.domcon;

import java.io.IOException;
import java.io.Writer;
import java.util.ArrayList;
import java.util.List;

import org._3pq.jgrapht.Edge;

import de.saar.chorus.domgraph.codec.CodecTools;
import de.saar.chorus.domgraph.codec.GraphOutputCodec;
import de.saar.chorus.domgraph.codec.MalformedDomgraphException;
import de.saar.chorus.domgraph.graph.DomGraph;
import de.saar.chorus.domgraph.graph.EdgeType;
import de.saar.chorus.domgraph.graph.NodeLabels;
import de.saar.chorus.domgraph.graph.NodeType;

public class DomconOzOutputCodec extends GraphOutputCodec {
    public DomconOzOutputCodec() {
        super();
        setName("domcon-oz");
        setExtension(".clls");
    }
    
    public void encode_graph(DomGraph graph, NodeLabels labels, Writer writer)
            throws IOException, MalformedDomgraphException {
        List<String> atoms = new ArrayList<String>();
        
        // iterate through the labelled nodes and output labelling atoms for them
        for( String node : graph.getAllNodes() ) {
            if( graph.getData(node).getType() == NodeType.LABELLED ) {
                StringBuilder sb = 
                    new StringBuilder("label(" + CodecTools.atomify(node) + " " 
                            + CodecTools.atomify(labels.getLabel(node)));
                
                
                List<String> children = graph.getChildren(node, EdgeType.TREE);
                if( !children.isEmpty() ) {
                    sb.append("(" + CodecTools.join(children, " ") + ")");
                }
                
                sb.append(")");
                
                atoms.add(sb.toString());
            }
        }
        
        // iterate through the dominance edges and output dominance atoms for them
        for( Edge edge : graph.getAllEdges() ) {
            if( graph.getData(edge).getType() == EdgeType.DOMINANCE ) {
                atoms.add("dom(" + edge.getSource() + " " + edge.getTarget() + ")");
            }
        }
        
        writer.write("[" + CodecTools.join(atoms, " ") + "]");
        writer.flush();
    }
    
    
    
    
    
    

    public void print_header(Writer writer) throws IOException {
        writer.write("%%  autogenerated by Domgraph/Java (see utool.sourceforge.net for details)\n");
    }

    public void print_footer(Writer writer) throws IOException {
        writer.flush();
    }

    public void print_start_list(Writer writer) throws IOException {
        writer.write( "[\n");
    }

    public void print_end_list(Writer writer) throws IOException {
        writer.write("]\n");
    }

    public void print_list_separator(Writer writer) throws IOException {
    }
    


}
