use std::{fs, process::Command};

fn fixture(name: &str, extension: &str, contents: &str) -> std::path::PathBuf {
    let path =
        std::env::temp_dir().join(format!("utool-{name}-{}.{extension}", std::process::id()));
    fs::write(&path, contents).unwrap();
    path
}

#[test]
fn solve_uses_java_command_and_codec_options() {
    let input = fixture("solve", "clls", "[label(x f(x1)) label(y a) dom(x1 y)]");
    let output = Command::new(env!("CARGO_BIN_EXE_utool"))
        .args(["solve", "-O", "term-prolog", input.to_str().unwrap()])
        .output()
        .unwrap();
    assert_eq!(output.status.code(), Some(1)); // Java Utool: 1 means solvable.
    assert_eq!(String::from_utf8(output.stdout).unwrap(), "[f(a)]");
    fs::remove_file(input).unwrap();
}

#[test]
fn solvable_and_convert_match_java_shapes() {
    let input = fixture("operations", "clls", "[label(x a)]");
    let solvable = Command::new(env!("CARGO_BIN_EXE_utool"))
        .args(["solvable", "--nochart", input.to_str().unwrap()])
        .status()
        .unwrap();
    assert_eq!(solvable.code(), Some(1));
    let converted = Command::new(env!("CARGO_BIN_EXE_utool"))
        .args(["convert", "-O", "domgraph-dot", input.to_str().unwrap()])
        .output()
        .unwrap();
    assert!(converted.status.success());
    assert!(
        String::from_utf8(converted.stdout)
            .unwrap()
            .starts_with("digraph dominance_graph")
    );
    fs::remove_file(input).unwrap();
}

#[test]
fn solve_defaults_to_the_matching_domcon_codec() {
    let input = fixture("default-codec", "clls", "[label(x a)]");
    let output = Command::new(env!("CARGO_BIN_EXE_utool"))
        .args(["solve", input.to_str().unwrap()])
        .output()
        .unwrap();
    assert_eq!(output.status.code(), Some(1));
    let stdout = String::from_utf8(output.stdout).unwrap();
    assert!(stdout.starts_with("%%  autogenerated by Utool\n[\n"));
    assert!(stdout.contains("label(x a)"));
    fs::remove_file(input).unwrap();
}

#[test]
fn no_command_displays_java_style_help_successfully() {
    let output = Command::new(env!("CARGO_BIN_EXE_utool")).output().unwrap();
    assert!(output.status.success());
    let stderr = String::from_utf8(output.stderr).unwrap();
    assert!(stderr.contains("Usage: utool <subcommand>"));
    assert!(stderr.contains("Available subcommands:"));
    assert!(!stderr.contains("java -jar"));
}

#[test]
fn chain_specification_is_a_length_not_a_filename() {
    let output = Command::new(env!("CARGO_BIN_EXE_utool"))
        .args(["solve", "-I", "chain", "3", "-O", "term-prolog", "-n", "-s"])
        .output()
        .unwrap();
    assert_eq!(output.status.code(), Some(1));
    let statistics = String::from_utf8(output.stderr).unwrap();
    assert!(statistics.contains("Number of solved forms: 5"));
    assert!(statistics.contains("Time to build chart:"));
    assert!(statistics.contains("Enumerated 5 solved forms."));
    assert!(statistics.contains("Time to enumerate solutions:"));
    assert!(
        statistics.contains("ns")
            || statistics.contains("µs")
            || statistics.contains("ms")
            || statistics.contains(" s")
    );

    let invalid = Command::new(env!("CARGO_BIN_EXE_utool"))
        .args(["convert", "-I", "chain", "0", "-O", "domcon-oz"])
        .status()
        .unwrap();
    assert_eq!(invalid.code(), Some(193));
}
