use std::{fs, process::Command};

fn fixture(name: &str, extension: &str, contents: &str) -> std::path::PathBuf {
    let path =
        std::env::temp_dir().join(format!("utool-{name}-{}.{extension}", std::process::id()));
    fs::write(&path, contents).unwrap();
    path
}

#[test]
fn solve_uses_java_command_and_codec_options() {
    let input = fixture("solve", "clls", "[label(x f(x1)) label(y a) dom(x1 y)]");
    let output = Command::new(env!("CARGO_BIN_EXE_utool"))
        .args(["solve", "-O", "term-prolog", input.to_str().unwrap()])
        .output()
        .unwrap();
    assert_eq!(output.status.code(), Some(1)); // Java Utool: 1 means solvable.
    assert_eq!(String::from_utf8(output.stdout).unwrap(), "[f(a)]");
    fs::remove_file(input).unwrap();
}

#[test]
fn solvable_and_convert_match_java_shapes() {
    let input = fixture("operations", "clls", "[label(x a)]");
    let solvable = Command::new(env!("CARGO_BIN_EXE_utool"))
        .args(["solvable", "--nochart", input.to_str().unwrap()])
        .status()
        .unwrap();
    assert_eq!(solvable.code(), Some(1));
    let converted = Command::new(env!("CARGO_BIN_EXE_utool"))
        .args(["convert", "-O", "domgraph-dot", input.to_str().unwrap()])
        .output()
        .unwrap();
    assert!(converted.status.success());
    assert!(
        String::from_utf8(converted.stdout)
            .unwrap()
            .starts_with("digraph dominance_graph")
    );
    fs::remove_file(input).unwrap();
}

#[test]
fn classify_reports_all_bits_without_requiring_an_hnc_solver_graph() {
    let input = fixture("classify-non-hnc", "clls", "[label(x a) label(y b)]");
    let output = Command::new(env!("CARGO_BIN_EXE_utool"))
        .args(["classify", "-s", input.to_str().unwrap()])
        .output()
        .unwrap();
    // Weakly normal, normal, compact, compactifiable, and leaf-labelled;
    // disconnected graphs are not hypernormally connected.
    assert_eq!(output.status.code(), Some(47));
    let statistics = String::from_utf8(output.stderr).unwrap();
    assert!(statistics.contains("not hypernormally connected"));
    fs::remove_file(input).unwrap();
}

#[test]
fn convert_does_not_require_solver_applicability() {
    let input = fixture("convert-non-hnc", "clls", "[label(x a) label(y b)]");
    let output = Command::new(env!("CARGO_BIN_EXE_utool"))
        .args(["convert", "-O", "domgraph-dot", input.to_str().unwrap()])
        .output()
        .unwrap();
    assert!(output.status.success());
    assert!(
        String::from_utf8(output.stdout)
            .unwrap()
            .contains("digraph dominance_graph")
    );
    fs::remove_file(input).unwrap();
}

#[cfg(unix)]
#[test]
fn display_launches_the_sibling_companion_and_forwards_arguments() {
    use std::os::unix::fs::PermissionsExt;

    let directory = std::env::temp_dir().join(format!("utool-display-test-{}", std::process::id()));
    fs::create_dir_all(&directory).unwrap();
    let cli = directory.join("utool");
    let display = directory.join("utool-display");
    let arguments = directory.join("arguments.txt");
    fs::copy(env!("CARGO_BIN_EXE_utool"), &cli).unwrap();
    fs::write(
        &display,
        format!(
            "#!/bin/sh\nprintf '%s\\n' \"$@\" > '{}'\nexit 23\n",
            arguments.display()
        ),
    )
    .unwrap();
    fs::set_permissions(&display, fs::Permissions::from_mode(0o755)).unwrap();

    let output = Command::new(&cli)
        .args(["display", "--filter", "rules.rewrite", "graph.clls"])
        .output()
        .unwrap();
    assert_eq!(output.status.code(), Some(23));
    assert_eq!(
        fs::read_to_string(&arguments).unwrap(),
        "--filter\nrules.rewrite\ngraph.clls\n"
    );

    fs::remove_dir_all(directory).unwrap();
}

#[test]
fn solve_defaults_to_the_matching_domcon_codec() {
    let input = fixture("default-codec", "clls", "[label(x a)]");
    let output = Command::new(env!("CARGO_BIN_EXE_utool"))
        .args(["solve", input.to_str().unwrap()])
        .output()
        .unwrap();
    assert_eq!(output.status.code(), Some(1));
    let stdout = String::from_utf8(output.stdout).unwrap();
    assert!(stdout.starts_with("%%  autogenerated by Utool\n[\n"));
    assert!(stdout.contains("label(x a)"));
    fs::remove_file(input).unwrap();
}

#[test]
fn no_command_displays_java_style_help_successfully() {
    let output = Command::new(env!("CARGO_BIN_EXE_utool")).output().unwrap();
    assert!(output.status.success());
    let stderr = String::from_utf8(output.stderr).unwrap();
    assert!(stderr.contains("Usage: utool <subcommand>"));
    assert!(stderr.contains("Available subcommands:"));
    assert!(!stderr.contains("java -jar"));
}

#[test]
fn chain_specification_is_a_length_not_a_filename() {
    let output = Command::new(env!("CARGO_BIN_EXE_utool"))
        .args(["solve", "-I", "chain", "3", "-O", "term-prolog", "-n", "-s"])
        .output()
        .unwrap();
    assert_eq!(output.status.code(), Some(1));
    let statistics = String::from_utf8(output.stderr).unwrap();
    assert!(statistics.contains("Number of solved forms: 5"));
    assert!(statistics.contains("Chart construction"));
    assert!(statistics.contains("Chart size:"));
    assert!(statistics.contains("Language size: 5 solved forms"));
    assert!(statistics.contains("Time to build chart:"));
    assert!(!statistics.contains("Filtering"));
    assert!(statistics.contains("Enumerated 5 solved forms."));
    assert!(statistics.contains("Time to enumerate solutions:"));
    assert!(statistics.contains("solutions/sec)"));
    assert!(
        statistics.contains("ns")
            || statistics.contains("µs")
            || statistics.contains("ms")
            || statistics.contains(" s")
    );

    let invalid = Command::new(env!("CARGO_BIN_EXE_utool"))
        .args(["convert", "-I", "chain", "0", "-O", "domcon-oz"])
        .status()
        .unwrap();
    assert_eq!(invalid.code(), Some(193));
}

#[test]
fn filtering_reports_both_phases_only_with_statistics() {
    let input = fixture(
        "filter-report-input",
        "clls",
        "[label(x a(x1 x2)) label(y a(y1 y2)) label(p p) label(q q) label(r r) dom(x1 p) dom(y1 q) dom(x2 r) dom(y2 r)]",
    );
    let rules = fixture(
        "filter-report-rules",
        "rules",
        "a#1(X,a#2(Y,Z)) = a#2(Y,a#1(X,Z))",
    );
    let output = Command::new(env!("CARGO_BIN_EXE_utool"))
        .args([
            "solvable",
            "-s",
            "-f",
            rules.to_str().unwrap(),
            input.to_str().unwrap(),
        ])
        .output()
        .unwrap();
    assert_eq!(output.status.code(), Some(1));
    assert!(output.stdout.is_empty());

    let report = String::from_utf8(output.stderr).unwrap();
    assert_eq!(report.matches("Chart construction").count(), 1);
    assert_eq!(report.matches("Filtering").count(), 1);
    assert_eq!(report.matches("Chart size:").count(), 2);
    assert_eq!(report.matches("Language size:").count(), 2);
    assert!(report.contains("Language size: 2 solved forms"));
    assert!(report.contains("Language size: 1 solved forms"));
    assert!(report.contains("Time to build chart:"));
    assert!(report.contains("Time to filter chart:"));

    let quiet = Command::new(env!("CARGO_BIN_EXE_utool"))
        .args([
            "solvable",
            "-f",
            rules.to_str().unwrap(),
            input.to_str().unwrap(),
        ])
        .output()
        .unwrap();
    assert_eq!(quiet.status.code(), Some(1));
    assert!(quiet.stdout.is_empty());
    assert!(quiet.stderr.is_empty());

    fs::remove_file(input).unwrap();
    fs::remove_file(rules).unwrap();
}

#[test]
fn compound_input_suffixes_select_distinct_codecs_and_bare_pl_is_ambiguous() {
    let mrs = fixture(
        "compound-mrs",
        "mrs.pl",
        "psoa(h1,e2,[rel('rain',h3,[attrval('ARG0',e2)])],hcons([qeq(h1,h3)]))",
    );
    let holesem = fixture(
        "compound-holesem",
        "hs.pl",
        "some(A,and(label(A),pred1(A,rain,x)))",
    );
    let ambiguous = fixture("ambiguous", "pl", "some(A,hole(A))");
    for path in [&mrs, &holesem] {
        let status = Command::new(env!("CARGO_BIN_EXE_utool"))
            .args(["solvable", path.to_str().unwrap()])
            .status()
            .unwrap();
        assert_eq!(status.code(), Some(1), "{}", path.display());
    }
    let status = Command::new(env!("CARGO_BIN_EXE_utool"))
        .args(["solvable", ambiguous.to_str().unwrap()])
        .status()
        .unwrap();
    assert_eq!(status.code(), Some(151));
    for path in [mrs, holesem, ambiguous] {
        fs::remove_file(path).unwrap();
    }
}

#[test]
fn compound_output_suffix_selects_gxl_without_an_explicit_codec() {
    let input = fixture("gxl-output-input", "clls", "[label(x a)]");
    let output = fixture("gxl-output", "dg.xml", "");
    let status = Command::new(env!("CARGO_BIN_EXE_utool"))
        .args([
            "convert",
            "-o",
            output.to_str().unwrap(),
            input.to_str().unwrap(),
        ])
        .status()
        .unwrap();
    assert!(status.success());
    assert!(fs::read_to_string(&output).unwrap().contains("<gxl"));
    fs::remove_file(input).unwrap();
    fs::remove_file(output).unwrap();
}
